<a href="https://colab.research.google.com/github/pulapallyyashwanth/NUMPY/blob/main/NUM_PY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Basics  03-01-2025**

In [ ]:
#what is Numpy--->    Num  + py------>    Numpy vs Pyspark
#core library for sceintific computing in python
#The central object in Numpy is "Numpy Array's"
#what is Numpy array?
'''High performance, multi-dimensional data
structure object which is designed specifically to perform maths operations'''

'High performance, multi-dimensional data\nstructure object which is designed specifically to perform maths operations'

In [ ]:
#How many types array's do we have?
#1D--> 0 cols and presensence of rows(axis = 0)
#2D---> tabular data where it has both rows and columns
#3D--> it is multidimensional data structure where it has axis =0, axis = 1 and axis = 2

In [ ]:
#what are all different use cases of Numpy?
"""1. Dot product/ inner product
   2. matrix multipolication
   3. elemnt wise matrix product
   4. solving the linear systems
   5. inverse
   6. determinent
   7. choose the random numbers
   8. statistics """

'1. Dot product/ inner product\n   2. matrix multipolication\n   3. elemnt wise matrix product\n   4. solving the linear systems\n   5. inverse\n   6. determinent\n   7. choose the random numbers\n   8. statistics '

In [ ]:
#installation of Numpy
!pip install Numpy

In [ ]:
#import numpy
import numpy as np

In [ ]:
#how can we check the version of numpy
np.__version__

'1.26.4'

#central object is array

In [ ]:
l1 =[1,2,3,4]
a = np.array(l1)
print(a)
print(l1)
#diff b/w list and array?
#list--> []--> ordered, muttable, allows duplicates
#array-->[]--> orderes, immutable, allows the duplicates

[1 2 3 4]
[1, 2, 3, 4]


In [ ]:
a = np.array([1,2,3,4])
print(a)
#i want to know the shape of the array
a.shape  #-->(count_rows,count_columns)
#i want to know element data types in above array?
a.dtype
#i want to know the dimensionality of the array's?
a.ndim
#i want to know total no of elements in array
a.size
#i want to know the size in bytes, of each element?
a.itemsize

[1 2 3 4]


8

**04-01-2025**

**essential methods in Numpy**

In [ ]:
import numpy as np

In [ ]:
b = np.array([1,2,3])
#access the elements by using the index position numbers
print(b[0])
print(b[0:3])
print(b[::-1])
print(b[:])  #default indexing [start[0]:end n+1: step 1]
print(b[::])


In [ ]:
#i want to know the sum of elements in the array
print(sum(b))

6


In [ ]:
h = np.array([1,2,3,4,5,6,7,8,9])
#print the sum array h
print(sum(h))
print(h.sum())
#find the mean the of the array "h"
print(h.mean())
#find min number in array h
print(h.min())
#find the max number in array?
print(h.max())
"""a = ['cat','dog','cat']
import pandas as pd
df = pd.DataFrame(a)
df.mode()"""

In [ ]:
l = [1,2,3,4,5,6,7,8,9]
print(sum(l))
#print(l.sum())
l.append(10)
l

In [ ]:
a = np.array([1,2,3,4,5,1,3,4,1])
print(dir(a))
#Note:- arrays dont have mode

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

**Array vs list**

In [ ]:
#add new item to the list
l = [1,2,3,4,5,6,7,8,9]
l.append(10)
l

45


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
#Add new item to the array
a = np.array([1,2,3])
a.append(4)
a

In [ ]:
#replace items
a[0] = 5
print(a)

[5 2 3]


In [ ]:
#Note: array's are immutable where in array's we can replace the items but we cannot add or remove the items
#so the arry's are having fixed memory
#MISD:--> multiple input single destination

In [ ]:
#how can we add items in an array?
a = np.array([1,2,3])
b = np.append(a,4)
print(b)

[1 2 3 4]


In [ ]:
c = b + np.array(5)
#single number array is adding with each and every element in array is known as "Broad casting" method
print(c)

[6 7 8 9]


In [ ]:
#Vector addition:- adding two array's having equal number of elemnets  and same dimensions is known vector addition
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)

[5 7 9]
[ 4 10 18]


In [ ]:
l = [1,2,3]
#multiple of 2
for i in l:
  print(i*2,end=" ")

2 4 6 

In [ ]:
print(a*2)

In [ ]:
#find the sqrt for array's
print(a**0.5)

[1.         1.41421356 1.73205081]


In [ ]:
a = ['apple',1,5.8,4+6j]
b = np.array(a)
print(b)

['apple' '1' '5.8' '(4+6j)']


In [ ]:
b = [2+4j, 5+6j]
c = np.array(b)
d = np.insert(b,2,5+6j)
print(d)

[2.+4.j 5.+6.j 5.+6.j]


In [ ]:
print(dir(d))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

dot

In [ ]:
a = np.array([1,2])
b = np.array([3,4])
#sum of products of corresponding items
#when apply dot product check the array are same number of elements
dot = 0
for i in range(len(a)):
  dot += a[i]*b[i]
  print(dot)

In [ ]:
#easy methods
dot = np.dot(a,b)
dot

11

In [ ]:
dot = a.dot(b)
print(dot)

11


In [ ]:
dot = a@b
print(dot)

11


In [ ]:
#manul
c = a*b
d = np.sum(c)
print(d)

11


**06-01-2025**

In [ ]:
import numpy as np

In [ ]:
#create a 1d array from list
a = [1,2,3]
b = np.array(a)
print(b.ndim)

1


**Multidimensional array's**

In [ ]:
#create a 2d array
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(a)

2
[[1 2 3]
 [4 5 6]]


In [ ]:
print(a.itemsize)
print(a.shape)

8
(2, 3)


In [ ]:
#How can i access the elements from array?
#by using the index position number we can acces elemnts in array
#array[row_index value, column index value]
a = np.array([[1,2,3],[4,5,6]])
print(a[0])

[1 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#if i want to access the particular value from particular column and row
print(b[1,1])
print(b[1][1])
#print the "9" from above array
print(b[2,2])
print(b[2][2])

In [ ]:
#slicing:- accessing the range of characters
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
#i want to print the values present at 1st column
print(b[:,0])
#print all the column values in row zero
print(b[0])
# 0r the below one bothe are same
print(b[0,:])

**Transpose**--> change rows in to columns and columns in to rows

In [ ]:
h = np.array([[1,2,3],[4,5,6]])
print(h.shape)

(2, 3)


In [ ]:
u = h.T
print(u)

[[1 4]
 [2 5]
 [3 6]]


**Mtarix Multiplication**

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
#Note:- to apply matrix multiplication the arrays hasto be in same shape
c = a.dot(b)
print(c)
#print(a*b)   #element wise multiplication

[[13 16]
 [29 36]]
[[ 3  8]
 [15 24]]


In [ ]:
#broadcasting method:-
a = np.array([[1,2],[3,4]])
b = np.array([[2]])
print(a*b)

[[2 4]
 [6 8]]


In [ ]:
d = np.array([[4,5,6],[7,8,9]])
h = d.dot(b)      #inner dimesions has to be matched
print(h)

In [ ]:
A = d.T
A

array([[4, 7],
       [5, 8],
       [6, 9]])

In [ ]:
H = A.dot(b)
print(H)

In [ ]:
#Note:- when we apply the dot product for 2d array it has to be in same shape

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([1,2])
c = a.dot(b)
print(c)

[ 5 11]


**determinent**

In [ ]:
a = np.array([[1,2],[3,4]])
#find the det of a
#use   'np.linalg.det'
c = np.linalg.det(a)
print(c)
#determinent  --->  [(1x4)- (2x3)]

-2.0000000000000004


**inverse**

In [ ]:
a = np.array([[1,2],[3,4]])
d = np.linalg.inv(a)
print(d)

[[-2.   1. ]
 [ 1.5 -0.5]]


**diagonal**

In [ ]:
c = np.diag(a)
print(c)

[1 4]


In [ ]:
#diagonal on a vector returns diagonal matrix
d = np.diag([1,4])
print(d)

[[1 0]
 [0 4]]


**Boolean indexing**

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.ndim)
print(a.shape)
print(a)
print(a[:,1])

2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 2  6 10]


In [ ]:
#print the elements greater than 2 from above array
print(a[a>2])

[ 3  4  5  6  7  8  9 10 11 12]


In [ ]:
#HOW WE CAN APPLY CONDITION IN ARRAY?
#np.where(condition, true, false)
b = np.where(a>2, a, -1)
print(b)

[[-1 -1  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a = np.array([10,20,30,40,50,60,19,30,31,61])
#compute indices where the condition is true  . number has to divisible with 2
even  = np.argwhere(a%2==0).flatten()
print(even)
#you want to see the values
a_even = a[even]
print(a_even)

[0 1 2 3 4 5 7]
[10 20 30 40 50 60 30]


**07-01-2025**

In [ ]:
"""revision
1. Numpy array differences
2. why numpy arrays are faster
3. DOT product with 1d array and 2d array
4. how to explore an arrays?
     a.np.shape
     b.np.ndim
     c.np.size
     d.np.dtypes
     c.np.itemsize
5.Boolean indexing, broadcasting, transpose,dia,np.linalg.det(), np.linalg.inv()
     """


'revision\n1. Numpy array differences\n2. why numpy arrays are faster \n3. DOT product with 1d array and 2d array\n4. how to explore an arrays?\n     a.np.shape\n     b.np.ndim\n     c.np.size\n     d.np.dtypes\n     c.np.itemsize\n5.Boolean indexing, broadcasting, transpose     '

#Reshaping of an array

In [ ]:
#create an array of range of 1 to 7
import numpy as np

In [ ]:
a = np.arange(1,7)
print(a)

[1 2 3 4 5 6]


In [ ]:
#reshape the above array in to 2 rows and 3 columns?
b = a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


**New axis**

In [ ]:
#new axis:- used to create new axis  in the data
print(a.shape)
d = a[np.newaxis,:]
print(d)

(6,)
[[1 2 3 4 5 6]]


In [ ]:
d.shape

(1, 6)

In [ ]:
e = a[:,np.newaxis]
print(e)
e.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [ ]:
#whay we are using np.newaxis?
#needed when the model requiresthe data to be shaped in a certain manner
#Note:- Transpose can be applicable for 2d_array

#Concatenation

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11,12]])
#combine or concatenate the above 2 arrays in 1d-Array
c = np.concatenate((a,b,c),axis = 0)
print(c)
"""Note:  1. when 'axis= None' it returns 1d array
          2. when 'axis = 0' it adds second array values in to rows wise
          3. when 'axis = 1' it adds the second array values in to columns side by side"""

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11,12]])
#combine or concatenate the above 2 arrays in 1d-Array
c = np.concatenate((a,b,c),axis = 0)
print(c)
print(c[2,:])
print(c[:,1])

**Hstack**

In [ ]:
#Hstack:- stack array in sequence horizentally
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
#c = np.concatenate((a,b),axis=None)
c = np.hstack((a,b))
print(c)
c.shape

[1 2 3 4 5 6 7 8]


(8,)

**Vstack**:- add the sequence of tack array's vertically

In [ ]:
d = np.vstack((a,b))
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
d = np.concatenate((a,b),axis = 0)
d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
d = np.hstack((a,b))
d

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#copying

In [ ]:
a = np.array([1,2,3])
b = a
b[0] = 32
print(a)

[32  2  3]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 6
print(a)
#By using copy() if you make any chnages to new array the old array does not change

[1 2 3]


**Data Types**

In [ ]:
#How can you find data types in the array?
a = np.array([1,2,3])
a.dtype

dtype('int64')

In [ ]:
#store the above array in 32bits
#How can you find data types in the array?
a = np.array([1,2,3],dtype = np.int32)
a.dtype

dtype('int32')

In [ ]:
#convert the data in to float
a = np.array([1,2,3],dtype = np.float32)
a.dtype
a

array([1., 2., 3.], dtype=float32)

#Generating Arrays

In [ ]:
#generate an array of zeros which is having  2 rows and 3 cols?
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#generate an array of ones which is having 2 rows and 3 columns
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#generate an array of specific number with specific rows and values
c = np.full((3,3),5)
c

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#genrate an identity matrix
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [ ]:
#generate an array of numbers up to 10
e = np.arange(1,11)
print(e)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#linspace:- splits the data in to equal parts
h = np.linspace(0,10,5)
#np.lionspace(start,end,split_count)
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**08-01-2025**

In [ ]:
import numpy as np

In [ ]:
d = np.eye(3)
print(d)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)
#N---> rows
#M --> Count of columns
#K --> index from where the '1' can be set in column index
#print a matrix with 3*5 idetntity matrix
b = np.eye(5,M=5,k=0)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#what is the difference between np.identity and np.eye()
#Np.idenetity--> return 2D arrray with N*N Matrix
#Np.eye()--> return 2D array with N*N matrics and we can customize the nof rows and columns along with index k customisation

In [ ]:
#argwhere, argmin,argmax--> returns the indexes


#Random Numbers

In [ ]:
#Generate a random numbers uniformly distributed from 0 to 1?
a = np.random.random((3,2))
print(a)

[[0.21021959 0.52393732]
 [0.50132349 0.73108023]
 [0.8135013  0.07737604]]


In [ ]:
#Generate an array which is normally distributed?
#Normal distribution means---> mean, median,mode is same, variance is 1
b = np.random.randn(3,2)
print(b)

[[-0.35796343  0.43437784]
 [-0.79373043 -0.77052887]
 [ 0.86532147  1.08570375]]


In [ ]:
print(np.mean(b))
print(np.var(b))
print(np.std(b))

In [ ]:
#generate random.randn numbers upto 1000 samples  find the mean,varience and std
c = np.random.randn(1000)
print(c.mean(),c.var(),c.std())

-0.04030908653345233 1.0122432630911504 1.006103008191085


In [ ]:
#generate an random intgers from 10 to 20 in the size of 4*4
#random.randint(low, high=None, size=None, dtype=int)
d = np.random.randint(10, size = (4,4))
print(d)

[[5 4 4 4]
 [6 9 2 6]
 [7 4 0 9]
 [1 5 8 7]]


In [ ]:
d = np.random.randint(10,20,size=(4,4))
print(d)

In [ ]:
#generate a number up to 6 and divide in to size of 10
e = np.random.choice(7,size=10)
print(e)

[4 4 3 0 2 3 6 0 2 5]


In [ ]:
l = np.random.choice([1,2,3,4],size = 10)
print(l)

[3 1 3 3 1 1 2 2 1 1]


**solving linear equations**

In [ ]:
#2x1 + 3y1 = 0
#6x + 12y  = 5
a = np.array([[2,3],[6,12]])
b = np.array([0,5])
#  ax = B <==>  x = a**-1 b
x = np.linalg.inv(a).dot(b)
print(x)

[-2.5         1.66666667]


In [ ]:
#instead use another method
x = np.linalg.solve(a,b)
print(x)

[-2.5         1.66666667]


**09-10-2025**

#Overall revision

In [ ]:
#what is a numpy?
#How do you create a 1d array?
import numpy as np
arr = np.array([1,2,3,4])
print(arr.ndim)

1


In [ ]:
#what is difference between a list and Numpy array?
#arrays we cannot add extram items to exisiting array
#where as in list we can add new items to exiting list
#array's are having fixed memory
#arrays are homogenous and list is heterogenous

In [ ]:
#How do you check the shape and size of an numpy array?
""" np.size
    np.shape"""

In [ ]:
#How do you reshape an array?
a = np.array([1,2,3,4,5,6])
#change the above array in to 3 rows and 2 columns
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#How do you create an array of all zeros and all ones?
a = np.zeros((3,2))
print(a)
b = np.ones((4,4))
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#what is broad casting in Numpy?
#it allows the arthematic operation between arrays of different sizes
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([2])
print(a*b)   # try -->   +,-,%,**

[[ 2  4  6  8]
 [10 12 14 16]]


In [ ]:
#how can find the mean,median, std?
a = np.array([[1,2,3,4],[5,6,7,8]])
print(np.mean(a))

b = np.array([1,2,3,4,5,6,7,9])
print(np.median(b))

print('std for array a:',np.std(a))
print('std for array b:',np.std(b))

4.5
4.5
std for array a: 2.29128784747792
std for array b: 2.496873044429772


In [ ]:
#how can we utilize Numpy to quickly query our numerical data and perform actions based on boolean statement?
a = np.array([20,30,16,17,18,22,23,24,25,32])
#from the above array check the age group people who is having >= 18 print 'true' else 'flase'
b = np.where(a>=18, 'True','False')
print(b)

['True' 'True' 'False' 'False' 'True' 'True' 'True' 'True' 'True' 'True']


In [ ]:
#How can you compute the rolling statistics  using Numpy,  such as rolling mean?
from numpy.lib.stride_tricks import sliding_window_view
x = np.arange(6)
# print(x)
v = sliding_window_view(x,3)
print(v)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [ ]:
#generate a random number which is uniformaly distributed --> 0 to 1
a = np.random.random((3,2))
#b = np.random.uniform((3,2))
a

array([[0.08325375, 0.07151937],
       [0.44474394, 0.2327695 ],
       [0.5457058 , 0.78278745]])

In [ ]:
b = np.random.randn(3,2)
b

array([[ 0.85853889,  1.94582482],
       [-0.09463895, -0.02453082],
       [ 0.82172331,  0.42699185]])

In [ ]:
c = np.random.choice([1,2,3,4],size =10)
print(c)

[3 1 2 1 4 1 1 4 3 1]


In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a)
#access the '8'
print(a[1,2])
print(a[0,:])   #print the entire values of 1st column

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
8
[1 2 3 4 5]


In [ ]:
#what is a dot product?
#dimesions must be same and it equal of number of elements
a = np.array([[1,2,3,4],[1,2,3,4]])
b = np.array([[6,7,8,9],[9,7,6,5]])
c = b.T
d = np.dot(a,c)
print(d)

[[80 61]
 [80 61]]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
d = a @ b
print(d)

30


**File Handling**

In [ ]:
#except python file if you handle othe file like pdf,txt, excel is known as file handling
#to read other files in python, use  "open()"
#The file handling can be done in 4 modes
# a, r, w, x
#1.execution mode (x)--> it is used to create the file
trail = open('trail.txt','x')

In [ ]:
#2. write or  overwrite mode (w):-
f = open('trail.txt','w')
f.write("i am writing contenct in this file by using write mode")
f.close()

In [ ]:
#3. append mode -->a
f = open('trail.txt','a')
f.write('. i am adding extra informtion to this file')
f.close()

In [ ]:
#4.read mode (r) by default the open() is in read mode
f = open('trail.txt','r')
g = f.read()
print(g)

i am writing contenct in this file by using write mode. i am adding extra informtion to this file


In [ ]:
f = open('trail.txt','w')
f.write("hello i am overwriting this file")
f.close()

In [ ]:
#how to find duplicated data in numpy array
a = np.array([1,2,3,4,5,1,2,2,2])
b = np.unique(a)
print(b)

[1 2 3 4 5]
